export const LOADING = 'LOADING'

export const SET_UPLOAD_FILES = 'SET_UPLOAD_FILES'
export const UPLOAD_BEGIN = 'UPLOAD_BEGIN'
export const UPLOAD_FAILED = 'UPLOAD_FAILED'
export const UPLOAD_DONE = 'UPLOAD_DONE'

export const SET_DOWNLOAD_FILES = 'SET_DOWNLOAD_FILES'
export const DOWNLOAD_FAILED = 'DOWNLOAD_FAILED'
export const DOWNLOAD_BEGIN = 'DOWNLOAD_BEGIN'
export const DOWNLOAD_DONE = 'DOWNLOAD_DONE'

export const SET_UPDATE_FILES = 'SET_UPDATE_FILES'
export const UPDATE_BEGIN = 'UPDATE_BEGIN'
export const UPDATE_DONE = 'UPDATE_DONE'
export const UPDATE_FAILED = 'UPDATE_FAILED'

export const SET_DELETE_FILE = 'SET_DELETE_FILE'
export const DELETE_DONE = 'DELETE_DONE'
export const DELETE_FAILED = 'DELETE_FAILED'
